version: "3"
services:
  crd4ws:
    container_name: crd4ws
    build: .
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]
    restart: always